version: '3'
services:
    app:
        build: ./docker
        volumes:
            - ./app:/var/www/html
        networks:
            - default
            - front_bridge
        environment:
            - VIRTUAL_HOST=todo-app.hideri.net
            - LETSENCRYPT_HOST=todo-app.hideri.net
            - LETSENCRYPT_EMAIL=hori.hide1003@gmail.com
            - LETSENCRYPT_TEST=false # Let's Encryptのテストかどうかのフラグ 本番ではfalseにする (指定しないとテスト扱いになる)
        depends_on:
            - app-db
    app-db:
        image: mysql:5.7
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_app_db
            MYSQL_USER: todo_app_user
            MYSQL_PASSWORD: todo_app_pass
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - 3306:3306

networks:
    front_bridge:
            external: true
